### ISSUE TITLE
Model clipping

### ISSUE THREAD

**Issue by zsvan** [gamma1772/HorizontalPanes#5]
Please make the model 1pixel smaller than full cube because now it's clipping with neighbour blocks if placed like on the picture. :)
It's common issue with blocks that have opacity and visible texture on sides.
![2021-04-27_21 13 02](https://user-images.githubusercontent.com/17712352/116299227-b39c4880-a79d-11eb-811d-6b58a233a049.png)

**Comment by mdujovic17** [comment]
I'll take a look at it tomorrow, thanks for reporting it.

**Comment by mdujovic17** [comment]
Fixed in 1.1.1
